name: user
description: uses a builder
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  build: ^2.0.1
  build_config: ^1.0.0
  glob: ^2.0.2
  dart_style: ^2.2.2

dev_dependencies:
  build_runner: ^2.1.8
  my_builder:
    path: ./packages/my_builder
