builders:
  my_builder:
    import: "package:my_builder/my_builder.dart"
    builder_factories: [ "myBuilder" ]
    build_to: source
    auto_apply: root_package
    build_extensions: { 'data/data.json': [ 'src/output.dart' ] }
