targets:
  $default:
    builders:
      my_builder:
        options:
          prf: msh
        dev_options:
          prf: local
        generate_for:
          include:
            - data/data.json

builders:
  my_builder:
    import: "package:my_builder/my_builder.dart"
    builder_factories: [ "myBuilder" ]
    build_to: source
    auto_apply: root_package
    build_extensions: { 'data/data.json': [ 'src/output.dart' ] }
